name: Deploy

on:
  push:
    branches:    
      - blog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup Python-Dev
      run: sudo apt-get install python-dev libxml2-dev libxslt1-dev zlib1g-dev
    - name: Python Packages
      run: |
        python -m pip install pip -U
        python -m pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
        python -m pip config set install.trusted-host mirrors.aliyun.com
        # python -m pip install setuptools==33.1.1 
        # python -m pip install --default-timeout=50000 -r requirements.txt 
    - name: Setup Hexo
      run: npm install hexo-cli@4.3.0 -g
    - name: Node.js Packages
      run: npm install
    - name: Configure Git
      run: | 
       git config user.name "qinyuanpei"
       git config user.email "qinyuanpei@163.com"
    - name: Clean & Generate
      run: | 
       hexo clean
       git rev-parse HEAD > VERSION.txt
    - name: Deploy Github Pages
      run: |
       sudo rm _config.yml
       sudo mv config-salve.yml _config.yml
       hexo generate
       sudo cp README.md ./public/README.md
       sudo cp VERSION.txt ./public/VERSION.txt
       sudo mkdir /home/runner/work/publish
       sudo cp -r /home/runner/work/qinyuanpei.github.io/qinyuanpei.github.io/public/*  /home/runner/work/publish/
       cd /home/runner/work/publish
       sudo git init 
       sudo git branch -m master
       sudo git config user.name "qinyuanpei"
       sudo git config user.email "qinyuanpei@163.com"
       sudo git remote add origin -m master https://${GH_TOKEN}@${GH_REPO}
       sudo git add .
       sudo git commit -m "Update Blog By Github Actions"
       sudo git push --force --quiet https://${GH_TOKEN}@${GH_REPO} master:master  
      env:
        GH_REPO: github.com/qinyuanpei/qinyuanpei.github.io.git
        GH_TOKEN: ${{ secrets.CI_TOKEN }}
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        branch: 'master'
        force: true
    - name: Deploy Vercel
      run: |
       sudo rm _config.yml
       sudo mv config-master.yml _config.yml
       hexo generate
       # python readme.py https://blog.yuanpei.me
       sudo cp README.md ./public/README.md
       sudo cp VERSION.txt ./public/VERSION.txt
       sudo cp -r /home/runner/work/qinyuanpei.github.io/qinyuanpei.github.io/public/* /home/runner/work/publish/
       cd /home/runner/work/publish
       sudo git init 
       sudo git config user.name "qinyuanpei"
       sudo git config user.email "qinyuanpei@163.com"
       sudo git remote add origin -m master https://github.com/qinyuanpei/qinyuanpe.github.io
       sudo git add .
       sudo git commit -m "Update Blog By Github Actions"
      #  sudo git push --force --quiet "https://${{ secrets.CI_TOKEN }}@${GO_REF}" master:master    
      env:
        GH_REF: github.com/qinyuanpei/qinyuanpei.github.io
        CO_REF: github.com/qinyuanpei/blog.yuanpei.me
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
